version: '3'
services: 
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile
        image: reverseproxy:0.0.1
        container_name: nginx
        volumes: 
            - ./nginx/weeber.conf:/etc/nginx/conf.d/weeber.conf
            - ./nginx/myfacilities.conf:/etc/nginx/conf.d/myfacilities.conf
        networks:
            nginx:
                aliases: 
                    - reverseproxy
        ports: 
            - 80:80

networks: 
    nginx:
        ipam:
            config:
                - subnet: 192.168.0.0/24
