version: '3'
services: 
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            nginx:
                aliases: 
                    - reverseproxy
        ports: 
            - 80:80

networks: 
    nginx:
        ipam:
            config:
                - subnet: 192.168.0.0/24
