version: '3'
services: 
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/weeber:/etc/nginx/conf.d/
      - ./nginx/myfacilities:/etc/nginx/conf.d/
    networks:
      nginx:
        aliases: 
          - reverseproxy
    ports: 
      - 80:80
      - 443:443

networks: 
  nginx:
    driver: bridge
