version: '3'
services:
    database_nosql:
        image: mongo:4.2.2-bionic
        container_name: mydatabase_nosql
        volumes:
            - singapore_volume:/external
        command: --config /external/mydatabase_nosql/mongo.conf
        networks:
            default:
                ipv4_address: 192.168.0.7
        ports: 
            - "127.0.0.1:27017:27017"

volumes:
    singapore_volume:
        external: true

networks: 
    default:
        external:
            name: reverseproxy_nginx
