version: '3'
services:
    database_sql:
        image: mongo:4.2.2-bionic
        container_name: mydatabase_nosql
        networks:
            default:
                ipv4_address: 192.168.0.7
        ports: 
            - 27017:27017
networks: 
    default:
        external:
            name: reverseproxy_nginx

